name: Set up Space CLI
on: push

jobs:
  set-up-space-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Install Deta Space CLI & set SPACE_ACCESS_TOKEN environment variable
        shell: bash
        run: |
          curl -fsSL https://get.deta.dev/space-cli.sh | sh
          echo '/home/runner/.detaspace/bin' >> $GITHUB_PATH
          echo "SPACE_ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> $GITHUB_ENV
      - name: Check Space installation
        run: |-
          space help
